DROP TABLE IF EXISTS WATT_READ;

CREATE TABLE WATT_READ(
	DATA DATETIME PRIMARY KEY, 
	WATT INT
);

DROP TABLE IF EXISTS OBJECT_READ;

--CREATE TABLE OBJECT_READ(
--	DATA DATETIME PRIMARY KEY, 
--	PL TINYINT,
--	TYPE TINYINT,
--	STATE BOOLEAN
--);

CREATE TABLE OBJECT_READ(
	DATA_ON DATETIME PRIMARY KEY,
	DATA_OFF DATETIME,
	PL TINYINT,
	TYPE TINYINT
);

DROP TABLE IF EXISTS OBJECT_WATT;

CREATE TABLE OBJECT_WATT (
	DATA_ON DATETIME PRIMARY KEY,
	DATA_OFF DATETIME,
	PL TINYINT, 
	WATT INT
);